version: '3.9'
services:
  broker:
    image: eclipse-mosquitto
    volumes: 
      - "./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf"
      - "./mqtt/password:/mosquitto/config/password"
      - "./mqtt/acl:/mosquitto/config/acl"
    ports:
      - "1883:1883"
    restart: always
    hostname: broker